[2021-10-16 13:05:34,245] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: fourth_dag.get_gross_year_0 scheduled__2021-10-16T12:06:00+00:00 [queued]>
[2021-10-16 13:05:34,324] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: fourth_dag.get_gross_year_0 scheduled__2021-10-16T12:06:00+00:00 [queued]>
[2021-10-16 13:05:34,324] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-16 13:05:34,324] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-16 13:05:34,324] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-16 13:05:34,498] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): get_gross_year_0> on 2021-10-16 12:06:00+00:00
[2021-10-16 13:05:34,656] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fourth_dag', 'get_gross_year_0', 'scheduled__2021-10-16T12:06:00+00:00', '--job-id', '443', '--raw', '--subdir', 'DAGS_FOLDER/fourth_dag.py', '--cfg-path', '/tmp/tmps0cuzqi0', '--error-file', '/tmp/tmpr47_gyf2']
[2021-10-16 13:05:34,657] {standard_task_runner.py:77} INFO - Job 443: Subtask get_gross_year_0
[2021-10-16 13:05:34,593] {standard_task_runner.py:52} INFO - Started process 849 to run task
[2021-10-16 13:05:35,148] {logging_mixin.py:109} INFO - Running <TaskInstance: fourth_dag.get_gross_year_0 scheduled__2021-10-16T12:06:00+00:00 [running]> on host e03fb9e01fd8
[2021-10-16 13:05:35,633] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fourth_dag
AIRFLOW_CTX_TASK_ID=get_gross_year_0
AIRFLOW_CTX_EXECUTION_DATE=2021-10-16T12:06:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-16T12:06:00+00:00
[2021-10-16 13:05:35,687] {python.py:152} INFO - Done. Returned value was: ['$217.57 ', '2010\n']
[2021-10-16 13:05:35,805] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=fourth_dag, task_id=get_gross_year_0, execution_date=20211016T120600, start_date=20211016T130534, end_date=20211016T130535
[2021-10-16 13:05:35,924] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-16 13:05:36,086] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
