[2021-10-16 13:43:03,919] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: fourth_dag.get_gross_year_0 scheduled__2021-10-16T13:40:00+00:00 [queued]>
[2021-10-16 13:43:03,949] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: fourth_dag.get_gross_year_0 scheduled__2021-10-16T13:40:00+00:00 [queued]>
[2021-10-16 13:43:03,950] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-16 13:43:03,950] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-16 13:43:03,950] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-16 13:43:04,057] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): get_gross_year_0> on 2021-10-16 13:40:00+00:00
[2021-10-16 13:43:04,068] {standard_task_runner.py:52} INFO - Started process 2922 to run task
[2021-10-16 13:43:04,086] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fourth_dag', 'get_gross_year_0', 'scheduled__2021-10-16T13:40:00+00:00', '--job-id', '689', '--raw', '--subdir', 'DAGS_FOLDER/fourth_dag.py', '--cfg-path', '/tmp/tmpdn6a2cys', '--error-file', '/tmp/tmpwlzrduwv']
[2021-10-16 13:43:04,087] {standard_task_runner.py:77} INFO - Job 689: Subtask get_gross_year_0
[2021-10-16 13:43:04,189] {logging_mixin.py:109} INFO - Running <TaskInstance: fourth_dag.get_gross_year_0 scheduled__2021-10-16T13:40:00+00:00 [running]> on host e03fb9e01fd8
[2021-10-16 13:43:04,296] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fourth_dag
AIRFLOW_CTX_TASK_ID=get_gross_year_0
AIRFLOW_CTX_EXECUTION_DATE=2021-10-16T13:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-16T13:40:00+00:00
[2021-10-16 13:43:04,309] {python.py:152} INFO - Done. Returned value was: ['$92.60 ', '2007\n']
[2021-10-16 13:43:04,354] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=fourth_dag, task_id=get_gross_year_0, execution_date=20211016T134000, start_date=20211016T134303, end_date=20211016T134304
[2021-10-16 13:43:04,415] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-16 13:43:04,480] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
