[2021-10-16 13:05:02,429] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: fourth_dag.get_gross_year_0 scheduled__2021-10-16T11:24:00+00:00 [queued]>
[2021-10-16 13:05:02,471] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: fourth_dag.get_gross_year_0 scheduled__2021-10-16T11:24:00+00:00 [queued]>
[2021-10-16 13:05:02,472] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-16 13:05:02,472] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-16 13:05:02,472] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-16 13:05:02,536] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): get_gross_year_0> on 2021-10-16 11:24:00+00:00
[2021-10-16 13:05:02,553] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fourth_dag', 'get_gross_year_0', 'scheduled__2021-10-16T11:24:00+00:00', '--job-id', '286', '--raw', '--subdir', 'DAGS_FOLDER/fourth_dag.py', '--cfg-path', '/tmp/tmpdgmu7gul', '--error-file', '/tmp/tmpkweqe46y']
[2021-10-16 13:05:02,554] {standard_task_runner.py:77} INFO - Job 286: Subtask get_gross_year_0
[2021-10-16 13:05:02,547] {standard_task_runner.py:52} INFO - Started process 526 to run task
[2021-10-16 13:05:02,813] {logging_mixin.py:109} INFO - Running <TaskInstance: fourth_dag.get_gross_year_0 scheduled__2021-10-16T11:24:00+00:00 [running]> on host e03fb9e01fd8
[2021-10-16 13:05:03,171] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fourth_dag
AIRFLOW_CTX_TASK_ID=get_gross_year_0
AIRFLOW_CTX_EXECUTION_DATE=2021-10-16T11:24:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-16T11:24:00+00:00
[2021-10-16 13:05:03,217] {python.py:152} INFO - Done. Returned value was: ['$160.31 ', '2008\n']
[2021-10-16 13:05:03,294] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=fourth_dag, task_id=get_gross_year_0, execution_date=20211016T112400, start_date=20211016T130502, end_date=20211016T130503
[2021-10-16 13:05:03,356] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-16 13:05:03,452] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
