[2021-10-16 13:05:02,665] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: fourth_dag.get_gross_year_1 scheduled__2021-10-16T11:06:00+00:00 [queued]>
[2021-10-16 13:05:02,777] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: fourth_dag.get_gross_year_1 scheduled__2021-10-16T11:06:00+00:00 [queued]>
[2021-10-16 13:05:02,778] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-16 13:05:02,778] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-16 13:05:02,778] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-16 13:05:02,864] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): get_gross_year_1> on 2021-10-16 11:06:00+00:00
[2021-10-16 13:05:02,878] {standard_task_runner.py:52} INFO - Started process 535 to run task
[2021-10-16 13:05:02,917] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fourth_dag', 'get_gross_year_1', 'scheduled__2021-10-16T11:06:00+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/fourth_dag.py', '--cfg-path', '/tmp/tmp3b0og9rz', '--error-file', '/tmp/tmpgmju0wod']
[2021-10-16 13:05:02,917] {standard_task_runner.py:77} INFO - Job 293: Subtask get_gross_year_1
[2021-10-16 13:05:03,221] {logging_mixin.py:109} INFO - Running <TaskInstance: fourth_dag.get_gross_year_1 scheduled__2021-10-16T11:06:00+00:00 [running]> on host e03fb9e01fd8
[2021-10-16 13:05:03,422] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fourth_dag
AIRFLOW_CTX_TASK_ID=get_gross_year_1
AIRFLOW_CTX_EXECUTION_DATE=2021-10-16T11:06:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-16T11:06:00+00:00
[2021-10-16 13:05:03,454] {python.py:152} INFO - Done. Returned value was: ['$217.57 ', '2010\n']
[2021-10-16 13:05:03,541] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=fourth_dag, task_id=get_gross_year_1, execution_date=20211016T110600, start_date=20211016T130502, end_date=20211016T130503
[2021-10-16 13:05:03,655] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-16 13:05:03,755] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
