[2021-10-16 13:04:54,204] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: fourth_dag.get_gross_year_2 scheduled__2021-10-16T11:22:00+00:00 [queued]>
[2021-10-16 13:04:54,231] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: fourth_dag.get_gross_year_2 scheduled__2021-10-16T11:22:00+00:00 [queued]>
[2021-10-16 13:04:54,231] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-16 13:04:54,231] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-16 13:04:54,231] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-16 13:04:54,278] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): get_gross_year_2> on 2021-10-16 11:22:00+00:00
[2021-10-16 13:04:54,299] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fourth_dag', 'get_gross_year_2', 'scheduled__2021-10-16T11:22:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/fourth_dag.py', '--cfg-path', '/tmp/tmpieilk12p', '--error-file', '/tmp/tmp6t6p1ec2']
[2021-10-16 13:04:54,300] {standard_task_runner.py:77} INFO - Job 252: Subtask get_gross_year_2
[2021-10-16 13:04:54,289] {standard_task_runner.py:52} INFO - Started process 436 to run task
[2021-10-16 13:04:54,403] {logging_mixin.py:109} INFO - Running <TaskInstance: fourth_dag.get_gross_year_2 scheduled__2021-10-16T11:22:00+00:00 [running]> on host e03fb9e01fd8
[2021-10-16 13:04:54,567] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fourth_dag
AIRFLOW_CTX_TASK_ID=get_gross_year_2
AIRFLOW_CTX_EXECUTION_DATE=2021-10-16T11:22:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-16T11:22:00+00:00
[2021-10-16 13:04:54,590] {python.py:152} INFO - Done. Returned value was: ['$54.53 ', '2010\n']
[2021-10-16 13:04:55,005] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=fourth_dag, task_id=get_gross_year_2, execution_date=20211016T112200, start_date=20211016T130454, end_date=20211016T130455
[2021-10-16 13:04:55,076] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-16 13:04:55,172] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
