[2021-10-16 13:09:03,430] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: fourth_dag.get_gross_year_2 scheduled__2021-10-16T13:06:00+00:00 [queued]>
[2021-10-16 13:09:03,454] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: fourth_dag.get_gross_year_2 scheduled__2021-10-16T13:06:00+00:00 [queued]>
[2021-10-16 13:09:03,454] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-16 13:09:03,454] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-16 13:09:03,454] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-16 13:09:03,488] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): get_gross_year_2> on 2021-10-16 13:06:00+00:00
[2021-10-16 13:09:03,495] {standard_task_runner.py:52} INFO - Started process 1250 to run task
[2021-10-16 13:09:03,508] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fourth_dag', 'get_gross_year_2', 'scheduled__2021-10-16T13:06:00+00:00', '--job-id', '572', '--raw', '--subdir', 'DAGS_FOLDER/fourth_dag.py', '--cfg-path', '/tmp/tmpkvtxax3b', '--error-file', '/tmp/tmpmpu432h3']
[2021-10-16 13:09:03,509] {standard_task_runner.py:77} INFO - Job 572: Subtask get_gross_year_2
[2021-10-16 13:09:03,577] {logging_mixin.py:109} INFO - Running <TaskInstance: fourth_dag.get_gross_year_2 scheduled__2021-10-16T13:06:00+00:00 [running]> on host e03fb9e01fd8
[2021-10-16 13:09:03,662] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fourth_dag
AIRFLOW_CTX_TASK_ID=get_gross_year_2
AIRFLOW_CTX_EXECUTION_DATE=2021-10-16T13:06:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-16T13:06:00+00:00
[2021-10-16 13:09:03,676] {python.py:152} INFO - Done. Returned value was: ['$252.04 ', '2008\n']
[2021-10-16 13:09:03,720] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=fourth_dag, task_id=get_gross_year_2, execution_date=20211016T130600, start_date=20211016T130903, end_date=20211016T130903
[2021-10-16 13:09:03,758] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-16 13:09:03,836] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
